

BAD_FORMAT = 1
NOT_NEEDED = 2
NOT_PARSABLE = 3
TOO_COMPLEX = 4
INVALID_OPEN = 5
CORRECTLY_CLOSED = 6
OWN_COMMENT = 7
AUTHOR_BLOCKED = 8
BANNED_FROM_SUBREDDIT = 9
UNBALANCED = 10

ALREADY_PROCESSED = 20
ALREADY_REGISTERED = 21
REGISTERED = 22

ERROR = 30

CORRECTION_ABORTED = 40
CORRECTED = 41